// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("MathParser")]
[assembly: AssemblyDescription("")]
[assembly: Guid("2e287aff-2093-4e8b-ba20-d903805b87a9")]
