// <auto-generated />
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("MathParser")]
[assembly: AssemblyDescription("")]
[assembly: Guid("62d899b5-d04d-4e66-aec0-5c62cf22403b")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("MathParser.Tests")]
