// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("62d899b5-d04d-4e66-aec0-5c62cf22403b")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("MathParser.Tests")]
