// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("MathParser")]
[assembly: AssemblyCopyright("Copyright © 2016 John Gietzen")]
[assembly: ComVisible(false)]
